version: '3.8'

services:
  db:
    image: postgres:17.0
    container_name: postgres-17-tyg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tyg
      POSTGRES_USER: tyg
      POSTGRES_PASSWORD: tyg#admin@123
    ports:
      - "5432:5432"
    networks:
      - tyg_network

volumes:
  postgres_data:
    driver: local

networks:
  tyg_network:
    driver: bridge
