spring:
  application:
    name: tyg-investments
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/tyg
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    context-path: /tyg-investments



#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics
#
#

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000

logging:
  level:
    org:
      springframework:
        cloud:
          openfeign: debug
    feign:
      client: debug

app:
  config:
    currency-base: BRL
    decimal-places: 4

alpha-vantage:
  api-keys:
    - ${ALPHA_VANTAGE_API_KEY_0}
    - ${ALPHA_VANTAGE_API_KEY_1}
    - ${ALPHA_VANTAGE_API_KEY_2}
    - ${ALPHA_VANTAGE_API_KEY_3}
    - ${ALPHA_VANTAGE_API_KEY_4}
    - ${ALPHA_VANTAGE_API_KEY_5}
    - ${ALPHA_VANTAGE_API_KEY_6}
    - ${ALPHA_VANTAGE_API_KEY_7}
    - ${ALPHA_VANTAGE_API_KEY_8}
    - ${ALPHA_VANTAGE_API_KEY_9}
    - ${ALPHA_VANTAGE_API_KEY_10}

  base-url: https://www.alphavantage.co
  get-info-assets: /query?function=OVERVIEW&
  get-daily-time-series: /query?function=TIME_SERIES_DAILY&
  get-global-quote: /query?function=GLOBAL_QUOTE&
  get-etf-profile: /query?function=ETF_PROFILE&

currency-layer:
  api-key: ${CURRENCY_LAYER_API_KEY}
  base-url: https://api.currencylayer.com

exchangerate:
  base-url: https://v6.exchangerate-api.com/v6/${EXCHANGE_API_KEY}/latest/${app.config.currency-base}
